[build-system]
requires = [
    "setuptools",
    "wheel",
]
build-backend = "setuptools.build_meta"

[project]
name = "wexample-config"
version = "0.0.26"
description = "Helpers to manage dict types configurations."
authors = [
    { name = "weeger", email = "contact@wexample.com" },
]
requires-python = ">=3.6"
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
]
dependencies = [
    "pip-tools",
    "pydantic",
    "pytest",
    "wexample-helpers==0.0.26",
]

[project.readme]
file = "README.md"
content-type = "text/markdown"

[project.license]
text = "MIT"

[project.urls]
homepage = "https://github.com/wexample/python-config"

[tool.setuptools.packages.find]
include = [
    "*",
]
